export { ComponentAnalyzer } from "./component-analyzer";
export { detectRoutes } from "./route-detector";
export { classifyComponent, containsProviderPattern, DEFAULT_CLASSIFICATION_RULES } from "./classifier";
export { GraphBuilder } from "./graph-builder";
export { RecursiveTraverser } from "./recursive-traverser";
export { SearchParamsAnalyzer } from "./search-params-analyzer";
export { RouteIntelligenceBuilder } from "./route-intelligence-builder";
export { CompositeDetector } from "./composite-detector";
export { SymbolResolver } from "./symbol-resolver";
export { Canonicalizer } from "./canonicalizer";
export { VerificationPass } from "./verification";
